### ISSUE TITLE
Requirement conflicts

### ISSUE THREAD

**Issue by jqiu23** [shaoyijia/VAG#1]
Directly run pip install -r requirements.txt will cause conflict due to the order of instructions.

```
adapter-transformers==2.2.0
sentence-transformers==2.2.2
transformers==4.11.3
```
sentence-transformers==2.2.2 will install transformer==4.35.2 and tokenizer==0.15.0, while transformers==4.11.3 and adapter-transformers==2.2.0 install tokenizer==0.10.3; although they can be successfully installed, the code gives ImportError due to overwriting issues.
This is the order I used to bypass the conflicts:
```
sentence-transformers==2.2.2
transformers==4.11.3
adapter-transformers==2.2.0
```
Using the instructions above, I can finally run the scripts. Is there any better way to do this?

Also, some certain packages installed higher version of torchvision that is not compatible with torch==1.10.0, which is compatible with torchvision==0.11.

**Comment by shaoyijia** [comment]
Thanks for your interest of this work and raising up the issue!

Yeah, I think you are right - it's better to install `transformers` before `adapter-transformers` as the latter is based on the former. Also, I think it's better to remove `torch` from `requirements.txt` as Pytorch now has a major update to v2.x and the Pytorch installation is device-dependent.

I just have a try on a new server and the following steps work for me:
1. Create a new conda environment: `conda create -n vag python==3.9`, `conda activate vag`
2. Install Pytorch based on your device version (check https://pytorch.org/get-started/locally/): 
```
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121
```
3. Install the modified requirements.txt: `pip install -r requirements.txt`. Here is the modified requirements.txt
```
accelerate==0.12.0
adapter-transformers==2.2.0
datasets==2.4.0
nlpaug==1.1.11
nltk==3.7
numpy==1.23.2
scikit-learn==1.1.2
transformers==4.11.3
sentence-transformers==2.2.2
tqdm==4.64.1
```

Also, I removed `from torch.utils.tensorboard import SummaryWriter` from `utils.py` since we didn't use `SummaryWriter` in the code and this is incompatible with the latest Pytorch version.

If this change works, please let me know and I'll update the repo accordingly. Thank you so much!

**Comment by jqiu23** [comment]
Thank you for the update!

I tried the modified requirements, but the code still throws error. I found the reason by swapping the order of adapter-transformers and sentence-transformers.

There is still a minor issue, though:
datasets==2.4.0 is installed with multiprocess==0.70.15 and dill==0.3.5.1 together, but the latter two are not compatible:
```
ERROR: multiprocess 0.70.15 has requirement dill>=0.3.7, but you'll have dill 0.3.5.1 which is incompatible.
```
Adding multiprocess==0.70.13 right after datasets==2.4.0 fixes the problem. I think it is just an issue with pipit.

So, the revised version of requirements.txt I am currently using is:
```
accelerate==0.12.0
datasets==2.4.0
multiprocess==0.70.13
nlpaug==1.1.11
nltk==3.7
numpy==1.23.2
scikit-learn==1.1.2
sentence-transformers==2.2.2
transformers==4.11.3
adapter-transformers==2.2.0
tqdm==4.64.1
```

**Comment by shaoyijia** [comment]
Oh yeah, my bad. I pasted the wrong requirements.txt... We should install transformers first because adapter-transformers is built on top of it; otherwise it'll install a certain transformers version by default.

I'll update the repo. Thank you so much!!
